// Do not edit this file directly. 
// Automatically generated from games.articles.media repository.
// GET /api/games/articles-media/dev-box

const articlesGames = [
  {
    "link": "https://four-frogs.articles.media",
    "name": "Four Frogs",
    "image": "https://cdn.articles.media/games/Four%20Frogs/thumbnail.webp"
  },
  {
    "link": "https://race-game.articles.media",
    "name": "Race Game",
    "image": "https://raw.githubusercontent.com/Articles-Joey/race-game/refs/heads/main/public/img/preview.webp"
  },
  {
    "link": "https://battle-trap.articles.media",
    "name": "Battle Trap",
    "image": "https://raw.githubusercontent.com/Articles-Joey/battle-trap/refs/heads/main/public/img/game-preview.webp"
  },
  {
    "link": "https://plinko.articles.media",
    "name": "Plinko",
    "image": "https://raw.githubusercontent.com/Articles-Joey/plinko/refs/heads/main/public/img/background.webp"
  },
  {
    "link": "https://blackjack.articles.media",
    "name": "Blackjack",
    "image": "https://raw.githubusercontent.com/Articles-Joey/blackjack/refs/heads/main/public/img/game-preview.webp"
  },
  {
    "link": "https://eager-eagle.articles.media",
    "name": "Eager Eagle",
    "image": "https://raw.githubusercontent.com/Articles-Joey/eager-eagle/refs/heads/main/public/img/preview.webp"
  },
  {
    "link": "https://assets-gallery.articles.media",
    "name": "Assets Gallery",
    "image": "https://raw.githubusercontent.com/Articles-Joey/assets-gallery/main/public/img/game-preview.gif"
  },
  {
    "link": "https://glass-ceiling.articles.media",
    "name": "Glass Ceiling",
    "image": "https://cdn.articles.media/games/Glass Ceiling/preview.webp"
  },
  {
    "link": "https://usa-tycoon.articles.media",
    "name": "USA Tycoon",
    "image": "https://cdn.articles.media/games/USA Tycoon/preview.webp"
  },
  {
    "link": "https://carousel-of-progress.articles.media",
    "name": "Carousel of Progress",
    "image": "https://cdn.articles.media/games/Carousel of Progress/thumbnail.jpg"
  },
  {
    "link": "https://pinball.articles.media",
    "name": "Pinball",
    "image": "https://raw.githubusercontent.com/Articles-Joey/pinball/main/public/img/game-preview.gif"
  },
  {
    "link": "https://ocean-rings.articles.media",
    "name": "Ocean Rings",
    "image": "https://cdn.articles.media/games/Ocean Rings/video-preview.gif"
  },
  {
    "link": "https://school-run.articles.media",
    "name": "School Run",
    "image": "https://cdn.articles.media/games/School Run/preview.webp"
  },
  {
    "link": "https://move-match.articles.media",
    "name": "Move Match",
    "image": "https://cdn.articles.media/games/Move Match/move-match-thumbnail.jpg"
  },
  {
    "link": "https://cannon.articles.media",
    "name": "Cannon",
    "image": "https://cdn.articles.media/games/Cannon/cannon-thumbnail.jpg"
  },
  {
    "link": "https://death-race.articles.media",
    "name": "Death Race",
    "image": "https://cdn.articles.media/games/Death Race/death-race-thumbnail.jpg"
  },
  {
    "link": "https://tag.articles.media",
    "name": "Tag",
    "image": "https://raw.githubusercontent.com/Articles-Joey/tag/refs/heads/main/public/img/preview.webp"
  },
  {
    "link": "https://ice-slide.articles.media",
    "name": "Ice Slide",
    "image": "https://cdn.articles.media/games/Ice Slide/ice-slide-thumbnail.jpg"
  },
  {
    "link": "https://8-ball-pool.articles.media",
    "name": "8 Ball Pool",
    "image": "https://raw.githubusercontent.com/Articles-Joey/8-ball-pool/refs/heads/main/public/img/game-preview.webp"
  },
  {
    "link": "https://parkour.articles.media",
    "name": "Parkour",
    "image": "https://cdn.articles.media/games/Parkour/parkour-thumbnail.png"
  },
  {
    "link": "https://tug-of-war.articles.media",
    "name": "Tug of War",
    "image": "https://cdn.articles.media/games/Tug of War/tug-of-war-thumbnail.png"
  },
  {
    "link": "https://platformer-escape.articles.media",
    "name": "Platformer Escape",
    "image": "https://cdn.articles.media/games/Platformer Escape/preview.webp"
  },
  {
    "link": "https://jungle-vines.articles.media",
    "name": "Jungle Vines",
    "image": "https://cdn.articles.media/games/Jungle Vines/preview.webp"
  },
  {
    "link": "https://treasure-dive.articles.media",
    "name": "Treasure Dive",
    "image": "https://cdn.articles.media/games/Treasure Dive/treasure-dive-thumbnail.png"
  },
  {
    "link": "https://memory-game.articles.media",
    "name": "Memory Game",
    "image": "https://raw.githubusercontent.com/Articles-Joey/memory-game/refs/heads/main/public/img/preview.webp"
  },
  {
    "link": "https://catching-game.articles.media",
    "name": "Catching Game",
    "image": "https://raw.githubusercontent.com/Articles-Joey/catching-game/refs/heads/main/public/img/preview.webp"
  },
  {
    "link": "https://stop-the-thieves.articles.media",
    "name": "Stop the Thieves",
    "image": "https://cdn.articles.media/games/Stop the Thiefs/preview.webp"
  },
  {
    "link": "https://assassin.articles.media",
    "name": "Assassin",
    "image": "https://cdn.articles.media/games/Assassin/assassin-thumbnail.webp"
  },
  {
    "link": "https://trash-chute.articles.media",
    "name": "Trash Chute",
    "image": "https://cdn.articles.media/games/Trash Chute/trash-chute-preview.webp"
  },
  {
    "link": "https://spleef.articles.media",
    "name": "Spleef",
    "image": "https://raw.githubusercontent.com/Articles-Joey/spleef/refs/heads/main/public/img/background.webp"
  }
]

export default articlesGames